"""document

Revision ID: 90263e20bfba
Revises: 58f9570501df
Create Date: 2024-03-25 14:27:47.094128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90263e20bfba'
down_revision: Union[str, None] = '58f9570501df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('document',
                  sa.Column('title', sa.String(), nullable=False),
                  sa.Column('description', sa.Text(), nullable=True),
                  sa.Column('user_id', sa.Integer(), nullable=False),
                  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                  sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                  sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                  sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                  sa.PrimaryKeyConstraint('id'))
  op.create_table('note_document',
                  sa.Column('note_id', sa.Integer(), nullable=False),
                  sa.Column('document_id', sa.Integer(), nullable=False),
                  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                  sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                  sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                  sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
                  sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
                  sa.PrimaryKeyConstraint('id'))
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('note_document')
  op.drop_table('document')
  # ### end Alembic commands ###
